{% set name = "streamtracer" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: af9d916bf2500afa47b403f9fb17b13792d0041dfe4a8b9451a523a65221c739

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - packaging
    - numpy >=1.23

test:
  imports:
    - streamtracer
  commands:
    - pip check
    - pytest --pyargs streamtracer
  requires:
    - pip
    - pytest
    - pytest-doctestplus

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - STBadman
    - cadair
    - dstansby
    - jgieseler
