{% set name = "streamtracer" %}
{% set version = "2.1.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamtracer-{{ version }}.tar.gz
  sha256: 57e6f5e5502779aa3b07e3a6676fa19edd4c1f0f4d6e54725e44e7fb2603b4d7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=0.13,<0.14
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - streamtracer
  commands:
    - pip check
    - pytest --pyargs streamtracer
  requires:
    - pip
    - pytest
    - pytest-doctestplus

about:
  home: https://streamtracer.readthedocs.io/en/latest/
  summary: Fast streamline tracing in python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - STBadman
    - cadair
    - dstansby
    - jgieseler
